export { cssLoader } from './cssLoader'
export { tsLoader } from './tsLoader'
export { fontsLoader } from './fontsLoader'
export { resourceLoader } from './resourceLoader'
export { babelLoader } from './babelLoader'
