#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier
yarn test:format ||
(
  echo '🤢🤮🤢🤮 Prettier Check Failed 🤢🤮🤢🤮
    Run yarn format, add changes and try commit again.';
  false;
)

# Check ESLint
yarn test:lint ||
(
  echo '😤🏀👋😤 ESLint Check Failed 😤🏀👋😤 
    Make the required changes listed above, add changes and try to commit again.'
  false; 
)

yarn test:style || 
(
  echo '😤🏀👋😤 Stylelint Check Failed 😤🏀👋😤 
    Make the required changes listed above, add changes and try to commit again.'
  false; 
)

# Check tsconfig
yarn test:types ||
(
  echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
    Make the changes required above.'
  false;
)

echo '🤔🤔🤔🤔... Trying to build now. 🤔🤔🤔🤔'

yarn build ||
(
  echo '❌👷🔨❌ Because your build failed ❌👷🔨❌
    Next build failed: View the errors above to see why. 
  '
  false;
)

echo '✅✅✅✅ You win!!! I am committing this now. ✅✅✅✅'